// Dependencies
import './tasks/build';
import './tasks/clean';
import './tasks/connect';
import './tasks/dist';
import './tasks/default';
import './tasks/lint';
import './tasks/release';
import './tasks/run';
import './tasks/script';
import './tasks/style';
import './tasks/test';
import './tasks/watch';
